/**
 * Publish client — publishes standalone HTML of an agenda to a public URL.
 *
 * Two-step process: saving an agenda does NOT update the public link.
 * The user must explicitly publish (or re-publish) to push changes live.
 *
 * Storage:  CF KV with `pub:{slug}` key, owned by the user's sync key.
 * Serving:  Worker route `GET /:slug.html` returns the HTML directly.
 */

import type { Agenda } from '../types';
import { getApiUrl } from './sync-client';
import { hashPhrase, getSavedPhrase } from './passphrase';
import { getLocale } from '../i18n';

/* ─── Slug generation ─── */

/** Generate a URL-friendly slug from the agenda header fields. */
export function generateSlug(agenda: Agenda): string {
  const parts = [
    agenda.header.vendorName,
    agenda.header.customerNumber,
    agenda.header.projectName,
    'agenda',
  ].filter(Boolean);

  return (
    parts
      .join('-')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')   // non-alphanumeric → hyphen
      .replace(/^-+|-+$/g, '')        // trim leading/trailing hyphens
      .slice(0, 80) || 'untitled-agenda'
  );
}

/* ─── Standalone HTML ─── */

/**
 * Wrap rendered agenda HTML in a complete standalone document.
 * @param innerHtml - the output of `renderAgendaHTML(agenda)` from preview-view
 * @param agenda    - used only for the `<title>` tag
 */
export function wrapStandaloneHTML(innerHtml: string, agenda: Agenda): string {
  const title = [agenda.header.vendorName, agenda.header.projectName]
    .filter(Boolean)
    .join(' — ') || 'Agenda';

  return `<!DOCTYPE html>
<html lang="${getLocale()}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${esc(title)}</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
      max-width: 820px;
      margin: 0 auto;
      padding: 32px 24px;
      color: #333;
      background: #fafafa;
      line-height: 1.5;
    }
    @media print { body { background: #fff; padding: 0; } }
    @media (max-width: 600px) { body { padding: 16px 12px; } }
  </style>
</head>
<body>
${innerHtml}
  <footer style="margin-top:40px;padding-top:12px;border-top:1px solid #ddd;font-size:10px;color:#999;text-align:center;">
    Generated by Tempo Agenda Builder
  </footer>
</body>
</html>`;
}

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

/* ─── Publish / Unpublish API calls ─── */

export async function publishHTML(
  slug: string,
  html: string,
): Promise<{ ok: boolean; url: string; error?: string }> {
  const phrase = getSavedPhrase();
  if (!phrase) throw new Error('Sync not enabled');

  const key = await hashPhrase(phrase);
  const api = getApiUrl();

  const res = await fetch(`${api}/api/pub`, {
    method: 'PUT',
    headers: {
      'Content-Type': 'application/json',
      'X-Sync-Key': key,
    },
    body: JSON.stringify({ slug, html }),
  });

  if (!res.ok) {
    const body = (await res.json().catch(() => ({}))) as { error?: string };
    return { ok: false, url: '', error: body.error ?? `HTTP ${res.status}` };
  }

  return { ok: true, url: getPublicUrl(slug) };
}

export async function unpublishAgenda(slug: string): Promise<boolean> {
  const phrase = getSavedPhrase();
  if (!phrase) return false;

  const key = await hashPhrase(phrase);
  const api = getApiUrl();

  const res = await fetch(`${api}/api/pub/${slug}`, {
    method: 'DELETE',
    headers: { 'X-Sync-Key': key },
  });

  return res.ok;
}

/** Build the public URL for a given slug. */
export function getPublicUrl(slug: string): string {
  return `${getApiUrl()}/${slug}.html`;
}
